### ISSUE TITLE
volume docs

### ISSUE THREAD

**Issue by steven-murray** [BellaNasirudin/py21cmmc_fg#11]
The ``volume`` method should have a bit more explanation in terms of what its doing, in the docstring. We could add an equation to the Notes section, and outline some of the assumptions (i.e. is it taking volume at zmid, weighted by beam or not? etc.)

**Comment by steven-murray** [comment]
From our previous discussion, what really should be the volume factor? Actually, if we ingest data in the form of visibilities, I am going to suggest that we _don't_ do any volume normalisation. It is just an extra factor which will be applied precisely the same way to both data and model, and which doesn't depend on any model parameters. 

I guess the pushback on this is if we wanted to write out a power spectrum to file on every iteration for follow-up. Then it might be useful to write out something in standard units. But this seems to me like something we can get right in a future version. It is not necessary for the Bayesian estimator.

**Comment by BellaNasirudin** [comment]
Are we totally getting rid of the volume factor then?
