### ISSUE TITLE
should weights be squared when averaging power?

### ISSUE THREAD

**Issue by steven-murray** [BellaNasirudin/py21cmmc_fg#15]
Just wondering if when averaging power: Pbar = (1/\sum w_i) \sum w_i P_i, the w_i should rather be squared? The weights are the weights of visibilities, and P is the square of the visibility.

**Comment by BellaNasirudin** [comment]
Do we also need to sum the weights when we do the fft over frequency?

**Comment by steven-murray** [comment]
Yes we do, though that is a separate issue: https://github.com/BellaNasirudin/py21cmmc_fg/issues/12

**Comment by steven-murray** [comment]
this is fixed in 13424f073f97de1faa498ad7988ba50a4b5bf3d4.
