### ISSUE TITLE
more comprehensive "summary" plot

### ISSUE THREAD

**Issue by BellaNasirudin** [BellaNasirudin/py21cmmc_fg#20]
From a "samples" object, aside from the existing plots, make :
1.a "signal to noise" plot of the 2D power spectrum (where noise is the std. dev. with fg and thermal noise as applicable)
2. an example covariance matrix (at a single u)

**Comment by steven-murray** [comment]
This *can* be done from a samples object (if the covariance is stored every
iteration) but that is an inefficient way to do it. Probably better to grab
the covariance from the noise file. This is the file that contains exactly
the output of "define_noise". I added this method in my latest push.

Sorry I know using samples was my original suggestion 😀

**Comment by BellaNasirudin** [comment]
Done 7b3ce4d9067a52a53021aa28684de998eb2d2487
commit 7284010564f7342cf8faa96b1d78bfd60193558a
