### ISSUE TITLE
conversion factor from K to Jy

### ISSUE THREAD

**Issue by steven-murray** [BellaNasirudin/py21cmmc_fg#6]
The conversion factor may depend on the effective area of the telescope (and by default it does). However, this is something that the telescope knows about, not the foregrounds. I think it should be in the CoreInstrumental class. However, it is also required in the Foreground class, unless we have a way to create the point-sources directly in mK. 

Thoughts?

**Comment by steven-murray** [comment]
To summarize previous discussions, we really shouldn't use Aeff at all. It is only there to approximate the effects of the beam-weighted observation area. We account for this by _actually using_ the beam in our integrations and volume. We should therefore go through and rectify this.

**Comment by BellaNasirudin** [comment]
I am working on this now. This will mean changing the units of foregrounds from Jy to mK using the Rayleigh-Jeans law:

S [Jy] = 10^26*2*k_B*T/lambda^2*omega

where omega is supposed to be the area (of beam or observation). Should I leave this in the core?

**Comment by steven-murray** [comment]
I _think_ you don't need the Omega, because our units for the FG are Jy/sr, right? I would convert the Jy --> K in the foreground core and add up in mK. Then in the instrumental core, convert from mK --> Jy. But it's probably just as good to do mk --> Jy in the FG core (then you don't need a conversion in the instrumental core). Up to you.

**Comment by steven-murray** [comment]
No, it is the 2D integral of the beam over the space: $\int\int e^{-l^2/(2\sigma^2)} dl$

**Comment by steven-murray** [comment]
BTW, how'd youwrite that sigma?!

**Comment by BellaNasirudin** [comment]
Okay, thanks will do that!

I copied σ (and the equation) from your paper. For some reason, it doesn't like epsilon so I had to type that.

**Comment by BellaNasirudin** [comment]
I have made the changes in cce9c6aa2a4e7d7aaeee2977c31d5a9d97790a49 a minute ago. It seems to run fine now.

Note that this is without the raw visibilities.. I just realized that you committed that earlier. This won't affect the commit you made that I haven't pulled, right?

**Comment by steven-murray** [comment]
Shouldn't. Just check.

Cheers,
Steven

________________________________
