### ISSUE TITLE
variance of power

### ISSUE THREAD

**Issue by steven-murray** [BellaNasirudin/py21cmmc_fg#8]
We need to calculate the variance (or perhaps covariance) of the power along with the power itself, to be used in weighting.

**Comment by steven-murray** [comment]
I have added the basic machinery to do this into powerbox (>=v0.5.2), and as of 03f80d67c6840e4e6a2b40d2719b5a01b68981e9, this is calculated when averaging the power. Nevertheless, I am not convinced that this will work okay. My initial tests on a non-foreground box indicate that the estimate of the variance is way off. It may be more useful to use an analytic covariance model.

**Comment by BellaNasirudin** [comment]
Do I still need to find the covariance of the foregrounds?

**Comment by steven-murray** [comment]
We definitely need the covariance, but I'm not sure of the best way of doing it -- whether by numerically finding it from simulation, or by analytically computing it. I was hoping the former would be good enough, but it might not be.
